select	
  "a12"."DESK_NAME",
  "a11"."DIM_CALENDAR_ID"  "DIM_CALENDAR_ID",
	"a12"."BOOK_NAME"  "BOOK_NAME",
	"a12"."PORTFOLIO_NAME"  "PORTFOLIO_NAME",
	"a13"."INDEX_NAME"  "INDEX_NAME",
  "a17".DELIVERY_MONTH_SEQ,
	"a13".COMMODITY_NAME "COMMODITY_NAME",
	"a18"."UNIT_NAME"  "INDEX_LIMIT_UNIT",
	sum("a11"."DELTA_DISC_ILU")  "DELTA"
from	Core.Preparation.ROCK_DB.ROCK_PROD.EXPORT."DWH_DELTA_FACT"	"a11"
	join	Core.Preparation.ROCK_DB.ROCK_PROD.EXPORT."DWH_PORTFOLIO_CURRENT_DIM"	"a12"
	  on 	("a11"."DIM_PORTFOLIO_CURRENT_ID" = "a12"."DIM_PORTFOLIO_CURRENT_ID")
	join	Core.Preparation.ROCK_DB.ROCK_PROD.EXPORT."DWH_INDEX_CURRENT_DIM"	"a13"
	  on 	("a11"."DIM_INDEX_CURRENT_ID" = "a13"."DIM_INDEX_CURRENT_ID")
	join	Core.Preparation.ROCK_DB.ROCK_PROD.EXPORT."DWH_DEAL_PDC_DIM"	"a14"
	  on 	("a11"."DIM_DEAL_PDC_ID" = "a14"."DIM_DEAL_PDC_ID")
	join	Core.Preparation.ROCK_DB.ROCK_PROD.EXPORT."DWH_CALENDAR_DELIVERY_DIM"	"a15"
	  on 	("a11"."DIM_DELIVERY_CAL_ID" = "a15"."DIM_CALENDAR_ID")
	join	Core.Preparation.ROCK_DB.ROCK_PROD.EXPORT."DWH_PARTY_DIM"	"a16"
	  on 	("a11"."DIM_EXTERNAL_LEGAL_ENTITY_PARTY_ID" = "a16"."DIM_PARTY_ID")
	join	Core.Preparation.ROCK_DB.ROCK_PROD.EXPORT."DWH_CALENDAR_DELIVERY_DIM"	"a17"
	  on 	(round("a11"."DELIVERY_MTH_GPT_ID",-2)+1 = "a17"."DIM_CALENDAR_ID")
	join	Core.Preparation.ROCK_DB.ROCK_PROD.EXPORT."DWH_UNIT_DIM"	"a18"
	  on 	("a11"."DIM_INDEX_LIMIT_UNIT_ID" = "a18"."DIM_UNIT_ID")
	join	Core.Preparation.ROCK_DB.ROCK_PROD.EXPORT."DWH_UNIT_DIM"	"a19"
	  on 	("a11"."DIM_INDEX_REPORTING_UNIT_ID" = "a19"."DIM_UNIT_ID")
	join	Core.Preparation.ROCK_DB.ROCK_PROD.EXPORT."DWH_UNIT_DIM"	"a110"
	  on 	("a11"."DIM_UNIT_ID" = "a110"."DIM_UNIT_ID")
	join	Core.Preparation.ROCK_DB.ROCK_PROD.EXPORT."DWH_INSTRUMENT_DIM"	"a111"
	  on 	("a11"."DIM_INSTRUMENT_ID" = "a111"."DIM_INSTRUMENT_ID")
	join	Core.Preparation.ROCK_DB.ROCK_PROD.EXPORT."DWH_CALENDAR_DIM"	"a112"
	  on 	("a11"."DIM_CALENDAR_ID" = "a112"."DIM_CALENDAR_ID")
where	(("a112"."CALENDAR_DATE" = '{cob}')
 and "a12"."INTERMEDIATE1_NAME" in ('OIL TRADING REPORTING')
 and "a13"."INDEX_NAME" not like 'IR_%'
 and "a110"."UNIT_NAME" not in ('Currency'))
 and DELIVERY_DATE > "a112"."CALENDAR_DATE"
group by	"a11"."DIM_CALENDAR_ID",
  "a12".DESK_NAME,
	"a12"."BOOK_NAME",
	"a12"."PORTFOLIO_NAME",
	"a13"."INDEX_NAME",
	"a18"."UNIT_NAME",
  "a17".DELIVERY_MONTH_SEQ,
	"a13".COMMODITY_NAME
ORDER BY DIM_CALENDAR_ID, BOOK_NAME, PORTFOLIO_NAME, INDEX_NAME